package com.example.listadragoes.api.controllers;
import com.example.listadragoes.api.entities.Dragao;
import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;


import com.example.listadragoes.api.repositories.DragaoRepository;

@RestController
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class DragaoController {

	@Autowired // This means to get the bean called Repository
    // Which is auto-generated by Spring, we will use it to handle the data
private DragaoRepository dragaoRepository;

@PostMapping(path="/add") // Map ONLY POST Requests
public @ResponseBody String addNewUser (String name
 ,String email) {
// @ResponseBody means the returned String is the response, not a view name
// @RequestParam means it is a parameter from the GET or POST request

Dragao n = new Dragao();
n.setName(name);
n.setType(email);
dragaoRepository.save(n);
return "Saved";
}

@GetMapping(path="/all")
public @ResponseBody Iterable<Dragao> getAllUsers() {
// This returns a JSON or XML with the users
return dragaoRepository.findAll();
}
}